env:
  browser: true
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  # - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:jsx-a11y/recommended'
  # - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - react-hooks
  - jsx-a11y
rules:
  arrow-body-style:
    - error
    - always
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
  block-spacing:
    - error
  brace-style:
    - error
    - 1tbs
  camelcase:
    - error
    - {
      properties: never
    }
  comma-spacing:
    - error
    - {
      before: false,
      after: true
    }
  function-call-argument-newline:
    - error
    - consistent
  indent:
    - error
    - tab
  init-declarations:
    - error
    - always
  implicit-arrow-linebreak:
    - error
    - beside
  keyword-spacing:
    - error
    - {
      before: true,
      after: true
    }
  key-spacing:
    - error
    - {
      beforeColon: false,
      afterColon: true,
      mode: strict
    }
  linebreak-style:
    - error
    - windows
  newline-after-var:
    - error
    - always
  no-constant-condition:
    - error
  no-const-assign:
    - error
  no-mixed-spaces-and-tabs:
    - error
  no-multi-spaces:
    - error
  no-shadow:
    - error
  no-trailing-spaces:
    - error
  no-undef:
    - error
  no-undefined:
    - error
  no-undef-init:
    - error
  no-var:
    - error
  no-whitespace-before-property:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  quotes:
    - error
    - backtick
  semi:
    - error
    - never
  space-before-blocks:
    - error
  spaced-comment:
    - error
    - always
  space-in-parens:
    - error
    - always
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  react/boolean-prop-naming:
    - error
  react/default-props-match-prop-types:
    - error
  react/destructuring-assignment:
    - error
  react/function-component-definition:
    - error
    - {
      namedComponents: arrow-function
    }
  react/no-access-state-in-setstate:
    - error
  react/no-array-index-key:
    - error
  react/no-children-prop:
    - error
  react/no-danger:
    - error
  react/no-danger-with-children:
    - error
  react/no-deprecated:
    - error
  react/no-did-mount-set-state:
    - error
  react/no-did-update-set-state:
    - error
  react/no-direct-mutation-state:
    - error
  react/no-find-dom-node:
    - error
  react/no-is-mounted:
    - error
  react/no-multi-comp:
    - error
  react/no-redundant-should-component-update:
    - warn
  react/no-render-return-value:
    - error
  react/no-set-state:
    - warn
  react/no-string-refs:
    - error
  react/no-this-in-sfc:
    - error
  react/no-typos:
    - warn
  react/no-unescaped-entities:
    - warn
  react/no-unknown-property:
    - error
  react/no-unused-prop-types:
    - warn
  react/no-unused-state:
    - warn
  react/no-will-update-set-state:
    - error
  react/prefer-es6-class:
    - error
  react/prefer-stateless-function:
    - error
  react/prop-types:
    - off
  react/react-in-jsx-scope:
    - off
  react/require-default-props:
    - warn
  react/require-optimization:
    - warn
  react/require-render-return:
    - error
  react/self-closing-comp:
    - error
  react/sort-comp:
    - warn
  react/state-in-constructor:
    - error
  react/style-prop-object:
    - error
  react/void-dom-elements-no-children:
    - error
  react/jsx-boolean-value:
    - error
    - never
  react/jsx-child-element-spacing:
    - warn
  react/jsx-closing-bracket-location:
    - error
  react/jsx-closing-tag-location:
    - error
  react/jsx-curly-newline:
    - error
  react/jsx-curly-spacing:
    - error
  react/jsx-equals-spacing:
    - error
  react/jsx-filename-extension:
    - error
    - {
      extensions: [.tsx]
    }
  react/jsx-first-prop-new-line:
    - error
  react/jsx-fragments:
    - error
  react/jsx-handler-names:
    - warn
  react/jsx-key:
    - error
  react/jsx-no-comment-textnodes:
    - error
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - warn
  jsx-a11y/anchor-is-valid:
    - off
  '@typescript-eslint/await-thenable':
    - off